apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: hello
    spec:
     containers:
     - name: hello
       image: "shashimls276/vaccination:35"
       ports:
       - containerPort: 8080        

---
apiVersion: v1
kind: Service
metadata:
	name: hello
	labels:
  		app: hello
spec:
ports:
  - port: 8081
    targetPort: 80
selector:
  app: hello
  tier: hello
type: LoadBalancer